config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'welcome#index'

	get 'welcome' => 'welcome#index'

#	resources :users, only: [:show] do
#		resources :movies, only: [:index, :show, :create, :destroy]
#		resources :reviews, only: [:create, :edit, :destroy]
#	end

  resources :users, only: [:show] do
    resources :movies, only: [:index, :show, :destroy], shallow: true do
      resources :reviews, only: [:create, :edit, :update, :destroy], shallow: true
    end
  end

  resources :movies, only: [:create]

	get 'search' => 'movies#search'
	get 'details/:imdb_id' => 'movies#details', as: 'details'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_and_belongs_to_many :movies
    has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user_page

  private
  def authenticate_user_page
  	if params[:user_id] != nil && params[:user_id].to_i != current_user.id
		flash[:alert] = "You are not signed in as that user!"
		redirect_to root_path
	end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :find_movie, only: [:show, :destroy]

  def index
    @movies = current_user.movies.sort{ |x, y| x.title <=> y.title }
  end

  def search
    @movie = Movie.new
    session[:return_to] ||= request.referer
    url = 'http://www.omdbapi.com/?s='
    search = params[:q]

    response = RestClient.get(url+search)

    data = JSON.parse(response.body)
    @results = data['Search']

    if @results
      render :results
    else flash[:alert] = "No results for #{search}."
      redirect_to welcome_path
    end
  end

  def create
    @movie = Movie.new(movie_params)
    imdb_id_temp = @movie.imdb_id
    if current_user.movies.any?{|movie| movie.imdb_id == imdb_id_temp }
      @movie = Movie.find_by(imdb_id: imdb_id_temp)
      flash[:notice] = "You have already favorited this movie."
    elsif Movie.all.any?{|movie| movie.imdb_id == imdb_id_temp}
      @movie = Movie.find_by(imdb_id: imdb_id_temp)
      current_user.movies << @movie
      flash[:notice] = "Movie favorited."
    else
      @movie = current_user.movies.build(movie_params)
      flash[:notice] = "Movie added to database and favorited."
    end

    if current_user.save
      redirect_to @movie
    else
      flash[:alert] = "Sorry, your movie could not be saved."
      redirect_to root_path
    end
  end

  def details
    @movie = Movie.new
    url = 'http://www.omdbapi.com/?i='
    search = params[:imdb_id]
    search += '&plot=full'

    response = RestClient.get(url+search)
    @movie_info = JSON.parse(response.body)
  end

  def show
    @review = Review.new
    @edit = params[:edit]
  end

  def destroy
    if current_user.movies.delete(@movie)
      flash[:alert] = "Movie removed from your favorites."
    else
      flash[:alert] = "Failed to remove from your favorites."
    end
    
    redirect_to user_movies_path(current_user)
  end

  private
  	def find_movie
  		@movie = Movie.find(params[:id])
  	end

  	def movie_params
  		params.require(:movie).permit(:title, :year, :plot, :imdb_id)
  	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @movie = Movie.find(params[:movie_id])
    if !( @movie.reviews.any?{|review| review.user_id.to_i == current_user.id } )
    	review = @movie.reviews.build(review_params)
    	review.user = current_user

    	if @movie.save
    		flash[:notice] = "Review created."
    	else
    		flash[:alert] = "Failed to save review."
     	end
     else
      flash[:notice] = "You already have a review for this movie."
    end
    redirect_to @movie
  end

  def edit
    review = Review.find(params[:id])
    movie = review.movie
    redirect_to movie_path(movie, edit: true)
  end

  def update
    
  end

  def destroy
    review = Review.find(params[:id])
    if review.user == current_user
      movie = review.movie
      if review.delete
       flash[:notice] = "Review deleted."
     else
       flash[:alert] = "Failed to delete review."
     end
   else
      flash[:notice] = "You are not signed in as that user."
   end

   redirect_to movie
  end

  private
  	def review_params
  		params.require(:review).permit(:body)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'IMDB App', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) || current_page?(welcome_path) %>"><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <li class="<%= 'active' if current_page?(user_movies_path(current_user))%>"><%= link_to 'Favorites', user_movies_path(current_user) %></li>
        <% end %>
      </ul>
      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      </p>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notices' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_favorite.html.erb
<%= simple_form_for @movie do |f| %>
	<%= f.hidden_field :title, :value => @movie_info['Title'] %>
	<%= f.hidden_field :year, :value => @movie_info['Year'] %>
	<%= f.hidden_field :plot, :value => @movie_info['Plot'] %>
	<%= f.hidden_field :imdb_id, :value => @movie_info['imdbID'] %>
	<%= f.button :submit, 'Favorite' %>
<% end %>

app/views/movies/details.html.erb
<h1><%= @movie_info['Title'] %></h1>
<p>Year: <%= @movie_info['Year'] %></p>
<p>Plot: <%= @movie_info['Plot'] %></p>
<% if user_signed_in? %>
	<% if current_user.movies.any?{ |movie| movie.imdb_id == @movie_info['imdbID'] } %>
		<p><%= link_to "Go to movie", movie_path(Movie.select{ |movie| movie.imdb_id == @movie_info['imdbID'] }.first) %></p>
	<% else %>
		<%= render 'movies/favorite' %>
	<% end %>
<% else %>
<%= render 'movies/favorite' %>
<% end %>
<%= link_to 'Back', 'javascript:history.go(-1);' %>

app/views/movies/index.html.erb
<h1>Movies</h1>
<% @movies.each do |movie| %>
	<p><%= link_to movie.title, movie %> | <%= movie.year %></p>
<% end %>

<%= link_to 'Back', 'javascript:history.go(-1);' %>

app/views/movies/results.html.erb
<h1>Search Results</h1>

<% @results.each do |movie| %>
	<%= movie['Title'] %><br>
	<%= movie['Year'] %>
	<%= link_to 'Details', details_path(movie['imdbID']) %>
	<hr>
<% end %>

<%= link_to 'Back', :back %>

app/views/movies/show.html.erb
<div class='row'>
	<div class='col-md-8'>
		<h1><%= @movie.title %></h1>
		<p>Year: <%= @movie.year %></p>
		<p>Plot: <%= @movie.plot %></p>
		<p><%= link_to 'Back', 'javascript:history.go(-1);' %> | 
		<%= link_to 'Unfavorite', movie_path, method: :delete %></p><br>
		<% if !( @movie.reviews.any?{|review| review.user_id.to_i == current_user.id } ) %>
			<h3>Add Review</h3>
			<%= render '/reviews/form' %>
		<% end %>
	</div>
	<div class='col-md-4'>
	<h1>Reviews</h1>
	<% @movie.reviews.each do |review| %>
		<% if review.user.id.to_i == current_user.id %>
			<% if @edit == 'true' %>
				<%= render '/reviews/form' %>
			<% else %>
				<p><%= review.body %></p>
				<%= link_to 'Edit', edit_review_path(review) %> | 
				<%= link_to 'Delete', review, method: :delete, data: {confirm: 'Are you sure?'} %>
			<% end %>
		<% else %>
			<p><%= review.body %></p>
		<% end %>
		<hr>
	<% end %>

	</div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@movie, @review] do |f| %>
   <%= f.input :body, label: false %>
   <%= f.button :submit %>
<%end%>

app/views/welcome/_search.html.erb
<%= form_tag("/search", method: "get") do %>
	<%= label_tag(:q, "Search for:") %>
	<%= text_field_tag(:q) %>
	<%= submit_tag("Search", class: "btn btn-sm btn-primary") %>
<% end %>

app/views/welcome/index.html.erb
<h1>IMDB API project</h1>

<%= render 'welcome/search' %>